version: "3.5"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0-1-ubi8
    hostname: zookeeper
    networks:
      - confluent
    ports:
      - "2181:2181"
      - "9999:9999"
    volumes:
      - ./app:/app
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: 127.0.0.1
  
  kafka:
    image: "confluentinc/cp-enterprise-kafka:5.5.0-1-ubi8"
    hostname: kafka
    networks:
      - confluent
    ports:
      - "9092:9092"
      - "4444:4444"
    volumes:
      - ./app:/app
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      CONFLUENT_METRICS_REPORTER_TOPIC_CREATE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      KAFKA_JMX_PORT: 4444
      KAFKA_JMX_HOSTNAME: 127.0.0.1

networks:
  confluent:
