version: "3.5"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0-1-ubi8
    hostname: zookeeper
    networks:
      - confluent
    ports:
      - "2181:2181"
      - "7071:7071"
    volumes:
      - ./agent:/agent
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: "-javaagent:/agent/jmx_prometheus_javaagent-0.3.1.jar=7071:/agent/zookeeper.yaml"

  prometheus:
    image: prom/prometheus:v2.5.0
    hostname: prometheus
    networks:
      - confluent
    ports:
      - "9090:9090/tcp"
    volumes:
      - ./prometheus:/etc/prometheus

networks:
  confluent:
