version: "3.5"
services:
  producer:
    image: cnfltraining/test-producer-net:1.0
    container_name: producer
    hostname: producer
    build: producer
    networks:
    - confluent
  consumer:
    image: cnfltraining/test-consumer-net:1.0
    container_name: consumer
    hostname: consumer
    build: consumer
    networks:
    - confluent

networks:
  confluent: